### PR TITLE
[WEBSITE-366] Add support for static nested classes

### PR DESCRIPTION
**Pull request by daniel-beck**
Work in progress: Also needs to be added to `javadoc`, `staplerdoc`.

### CODE REVIEW

**Comment by rtyler** [comment]
@daniel-beck If you'' bounce the version number in this PR, I can merge and cut a release immediately

**Comment by rtyler** [comment]
meh, i'll do it

**Comment by rtyler** [comment]
0.3.0 released

**Comment by daniel-beck** [comment]
@rtyler 
> Work in progress

😢

**Comment by rtyler** [comment]
:man_shrugging: 

no big deal

**Pull request merged**
