### PR TITLE
[WEBSITE-523] - Fix the macro for empty ID prefix

### PR DESCRIPTION
**Pull request by oleg-nenashev**
@jglick @bitwiseman

https://issues.jenkins-ci.org/browse/WEBSITE-523

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@bitwiseman There is https://github.com/jenkins-infra/asciidoctor-jenkins-extensions/blob/master/examples/jira.adoc with full documentation/examples

**Comment by oleg-nenashev** [comment]
@rtyler would you be available to release it or to explain the release process/required permissions to Ruby newbies like me? Thanks in advance!

**Comment by oleg-nenashev** [comment]
@rtyler @olblak would it be possible to merge and release it?

**Comment by olblak** [comment]
I can't release a new version but I can bring this topic in during the next infra meeting (Today)

**Pull request merged**
