### PR TITLE
Allow usage with Asciidoctor 2.*

### PR DESCRIPTION
**Pull request by zbynek**

### CODE REVIEW

**Comment by zbynek** [comment]
@rtyler could you please check?

**Comment by timja** [comment]
@rtyler could MarkW and I get access on this repo please?

**Comment by timja** [comment]
@slide looks like you have access for the PR itself at least ^.^

**Comment by timja** [comment]
@rtyler my rubygems account is timja, would be good if you could add me there ^.^.

Thanks

**Pull request merged**
